name: "Sops GitOps Github Action"
description: "A Github action to manage and maintain SOPS secrets for your repository"
author: "Weaveworks Community"
maintainer:
  - "Charles Sibbald"
runs:
  using: "docker"
  image: "docker://ghcr.io/weaveworks/sops-gitops-github-action:latest"
  args:
    - "${{ inputs.input1 }}"
    - "${{ inputs.input2 }}"
inputs:
  private_key:
    description: "Base64-encoded private GPG key"
    required: true
  public_keys:
    description: "Comma-separated list of base64-encoded public GPG keys"
    required: true
outputs:
  output1:
    description: "The first output value"
