name: Code Coverage

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  coverage:
    name: Code Coverage
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true

      - name: Install tarpaulin
        run: cargo install cargo-tarpaulin

      - name: Run code coverage
        run: |
          cargo tarpaulin --out Xml --timeout 120

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: target/tarpaulin/coverage.xml
          fail_ci_if_error: true
          verbose: true
