version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore(deps)"
      include: scope
    open-pull-requests-limit: 5
    ignore:
    # - dependency-name: "example-crate"
    #   versions: ["< 2.0.0"]

  - package-ecosystem: "rust"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore(rust-nightly)"
    open-pull-requests-limit: 1

  - package-ecosystem: "github-actions"
    directory: ".github/workflows"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore(actions)"
    open-pull-requests-limit: 3
